# Generated by Django 4.1.13 on 2024-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='avaialability',
            new_name='disponivel',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='product',
            name='meiaPorcao',
            field=models.BooleanField(default=True),
        ),
    ]
