# Generated by Django 4.1.13 on 2024-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_description_product_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='imagens/'),
        ),
    ]
