# Generated by Django 4.1.13 on 2024-02-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_product_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='name',
        ),
    ]
