# Generated by Django 4.1.13 on 2024-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_product_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='static/imagens/'),
        ),
    ]
