# Generated by Django 4.1.13 on 2024-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_product_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produto'},
        ),
    ]
