# Generated by Django 4.1.13 on 2024-02-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produto'},
        ),
    ]
