# Generated by Django 4.1.13 on 2024-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='static/imagens/'),
        ),
    ]
