# Generated by Django 4.1.13 on 2024-02-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_restaurante_end_time_restaurante_start_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'verbose_name_plural': 'Restaurante'},
        ),
    ]
