# Generated by Django 4.1.13 on 2024-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_restaurante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='city',
            field=models.CharField(default='Sem cidade inforamada', max_length=20),
        ),
    ]
