# Generated by Django 4.1.13 on 2024-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_restaurante_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='limite_entrega',
            field=models.IntegerField(default='0', verbose_name='Limite de Entrega'),
        ),
    ]
