# Generated by Django 4.1.13 on 2024-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_nome_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categoria'},
        ),
    ]
