# Generated by Django 4.1.13 on 2024-02-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
    ]
