# Generated by Django 4.1.13 on 2024-02-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faixas',
            options={'verbose_name_plural': 'Faixa'},
        ),
    ]
