# Generated by Django 4.1.13 on 2024-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0002_alter_faixas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixas',
            name='name',
            field=models.CharField(default='Faixa Nomear', max_length=20),
        ),
    ]
