# Generated by Django 4.1.13 on 2024-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cpf_client',
            field=models.CharField(max_length=11),
        ),
    ]
