# Generated by Django 4.1.13 on 2024-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidos_cpf_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARD', 'Cartão'), ('ENT', 'Pagamento na Entrega')], default='ENT', max_length=4),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status_pagamento',
            field=models.CharField(choices=[('PR', 'Processando'), ('AP', 'Pagamento Aprovado'), ('RE', 'Pagamento recusado')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status_pedido',
            field=models.CharField(choices=[('RE', 'Recebido'), ('PR', 'Em Produção'), ('SE', ' Saiu para entrega'), ('EN', 'ENTREGUE')], default='RE', max_length=2),
        ),
    ]
