# Generated by Django 4.1.13 on 2024-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_status_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
