# Generated by Django 4.1.13 on 2024-02-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_itempedido_faixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='faixa',
        ),
    ]
