# Generated by Django 4.1.13 on 2024-02-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_itempedido_faixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
