# Generated by Django 4.1.13 on 2024-02-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0003_faixas_name'),
        ('pedidos', '0008_alter_itempedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedido'},
        ),
        migrations.AddField(
            model_name='itempedido',
            name='faixa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='faixas.faixas'),
        ),
    ]
