# Generated by Django 4.1.13 on 2024-02-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0003_faixas_name'),
        ('pedidos', '0009_alter_itempedido_options_itempedido_faixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='faixa',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='faixa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='faixas.faixas'),
        ),
    ]
