# Generated by Django 4.1.13 on 2024-02-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0003_faixas_name'),
        ('pedidos', '0010_remove_itempedido_faixa_pedidos_faixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='address_client',
            field=models.TextField(verbose_name='Endereço do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='cpf_client',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='faixa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='faixas.faixas', verbose_name='Frete Faixa'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='name_client',
            field=models.CharField(max_length=20, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
