# Generated by Django 4.1.13 on 2024-02-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedidos_address_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='email_client',
            field=models.EmailField(blank=True, default='email@email.com.br', max_length=254, verbose_name='Email do Cliente'),
        ),
    ]
