# Generated by Django 4.1.13 on 2024-02-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meususuarios', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
