# Generated by Django 4.1.13 on 2024-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meususuarios', '0004_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'teste', 'verbose_name_plural': 'Usuário'},
        ),
    ]
